import Head from "next/head";
import Category from "../components/Category/Category";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Navbar from "../components/Navbar/Navbar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>JobMaster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="top">
        <Navbar />
        <Header />
        <Category />
        <Footer />
      </main>
    </div>
  );
}
